### ISSUE TITLE
Cannot read property 'vfs' of undefined

### ISSUE THREAD

**Issue by afanazmy** [bkniffler/react-pdfmake#1]
When I create a PDF from your example there is an error

> Cannot read property 'vfs' of undefined

And then, when I look your source code, I think there is a deprecated function or feature in pdfmake.

It is your code :
`const pdfMake = require('pdfmake/build/pdfmake');`
`const pdfFonts = require('pdfmake/build/vfs_fonts');`
`pdfMake.vfs = pdfFonts.pdfMake.vfs;`

I think there is an error in `pdfFonts.pdfMake.vfs`

**Comment by bkniffler** [comment]
Sorry you got this error, I've bumped the dependencies, should work fine now.

**Comment by biapar** [comment]
That is?
