### ISSUE TITLE
At least make a proper example

### ISSUE THREAD

**Issue by flaviouk** [bkniffler/react-pdfmake#2]
If this library is not ready, just mention it in the readme, I had to dig through your code to find out that every element returns null, thanks for that

**Comment by dewaleolaoye** [comment]
Ooooh damn, and this will be a great package if @bkniffler wishes to continue it. 
I had love to contribute

**Comment by bkniffler** [comment]
Added an example (https://react-pdfmake.netlify.app), bumped dependencies.
The return value of elements doesn't really matter, the magic is happening in convert.ts. Contributions are welcome, feel free to PR.
